### ISSUE TITLE
<input> inside dropdown doesn't work

### ISSUE THREAD

**Issue by rnons** [citizennet/purescript-halogen-select#36]
## Environment

* PureScript **[0.12]**
* Halogen **[master]**
* Select **[5.0 branch]**

## Current behavior

Because `mousedown` is prevented when using `setContainerProps`, text input inside dropdown doesn't work, cannot focus or input text into it.
A reproduce: https://rnons.github.io/halogen-select-issue/

## Expected behavior

Should be able to focus and input text into `<input>` inside dropdown.
In [halogen-day-picker](https://github.com/rnons/purescript-halogen-day-picker/blob/master/src/Halogen/DayPickerInput.purs#L194-L209), I used a `clickedInside` flag to decide visibility.

Since this is a `select` library, it's understandable if you don't want to support this case, just want to make sure. Thanks

**Comment by davezuch** [comment]
Hi @rnons, thanks for opening an issue. So the way Select works, all DOM events that trigger behaviors such as selection highlighting or whether visibility is on or off, they're bound to the [toggle or input props](https://github.com/citizennet/purescript-halogen-select/blob/master/src/Select/Setters.purs#L87-L91). That means those behaviors will only work as long as the toggle or input has focus, which is why we prevent default behavior on `mousedown`, because we don't want focus to leave our toggle/input element as long as the user is clicking inside the container.

If you want to have your search input inside the dropdown, there is a trick we use which you can see in action at the bottom of [this page](https://citizennet.github.io/purescript-ocelot/#typeaheads).

Basically you put your search (with input props attached) inside your dropdown container, but instead of conditionally rendering it, you conditionally show/hide it (we have an `"offscreen"` class that uses absolute positioning to hide an element off-screen). Then you just make your "toggle" element a `label`, which takes advantage of the label's default behavior of triggering focus on the first child input. That means clicking on the `label` will trigger focus on the child search element, which will switch `Visibility` to `On`, and then everything should just work.

A lightweight example:

```purescript
HH.label
  [ css "relative" ]
  [ HH.button_ "toggle"
  , HH.div
      [ css if visibility ==  Off then "offscreen" else "dropdown" ]
      [ HH.input setInputProps myInputProps
      , renderItems
      ]
   ]
```

```css
.relative { position: relative; }
.offscreen { position: absolute; left: -9999%; top: -9999%; }
.dropdown { position: absolute; left: 0; top: 100%; }
```

As an aside, I'm not sure if these fit your use-case, but we do have some datepickers implemented. They're open source, but coupled to our UI. See [here](https://citizennet.github.io/purescript-ocelot/#date-pickers) for UI examples, and [here](https://github.com/citizennet/purescript-ocelot/blob/master/ui-guide/Components/DatePickers.purs) for usage examples.

**Comment by rnons** [comment]
@davezuch Thank you for detailed answer. My case is a bit different, I only want to use Select as a dropdown library. I'm trying to render this [color picker](https://nonbili.github.io/purescript-halogen-color-picker/#Simple%20color%20picker) in a dropdown, it can have up to four text  inputs and other controls. It's alright, I'm going to write a simple dropdown component. Thanks
